# -*- coding: utf-8 -*-

USER_CREATE = 'Create new user'
USER_UPDATE = 'Update user'
USER_DELETE = 'Remove user'
USER_MANY = 'Get list of users'
USER_ONE = 'Get single user'
USER_DISABLE = 'Disable user account'
USER_ENABLE = 'Enable user account'
USER_MEMBERSHIPS = 'Get list of groups for user'
USER_PASSWORD = 'Sets new password'
USER_PW_NEVER_EXPIRES = 'Sets password-never-expires for user'
USER_UNLOCK = 'Unlocks the user account'

GROUP_CREATE = 'Create new group'
GROUP_UPDATE = 'Update group'
GROUP_DELETE = 'Remove group'
GROUP_MANY = 'Get list of groups'
GROUP_ONE = 'Get single group'
GROUP_MEMBER_ADD = 'Add user to group'
GROUP_MEMBER_DEL = 'Remove user from group'
GROUP_MEMBERS = 'Get list of members'
